### ISSUE TITLE
什么时候出cdn的sdk

### ISSUE THREAD

**Issue by rwx------** [huaweicloud/huaweicloud-sdk-go-v3#1]
我看go版本里没有cdn的sdk？大概什么时候能出来，还是说需要我自己撸？

**Comment by xionghao-hw** [comment]
你好，正在规划中。

**Comment by wuchen-huawei** [comment]
你好，CDN目前暂时没有接入SDK的计划，当前需要使用的话，可能需要你自己写代码使用。后续如果CDN有接入，会在这个Issue下再次回复。

**Comment by cupen** [comment]
附议～  万人血书！

**Comment by wuchen-huawei** [comment]
出了出了，快去康康！有问题提issue或者提工单都可以的 (*^▽^*)

API Explorer和示例代码地址：https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=CDN&api=CreateDomain
