### ISSUE TITLE
HTTP proxy config not working if username&password are not set

### ISSUE THREAD

**Issue by orangedeng** [huaweicloud/huaweicloud-sdk-go-v3#14]
As code https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/core/config/http_config.go#L110-L119

If username and password are not set, proxyUrl will be an empty string.

**Comment by Huaweicloud-SDK** [comment]
The SDK has fixed this problem using your suggestion since version 0.0.34-rc, thanks for your PR, and sorry for late reply.
