### ISSUE TITLE
How to get a server's detail info?

### ISSUE THREAD

**Issue by RainbowMango** [huaweicloud/huaweicloud-sdk-go-v3#2]
Which ECS API should I take if I want to get the ECS detail information by `server name` or `server ID`?

Is the `NovaShowServer` used to get a server by ID? If yes, how can I get the `OpenStackAPIVersion` required by `model.NovaShowServerRequest`?
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/0281b9734f0f95ed5565729e54d96e9820262426/services/ecs/v2/ecs_client.go#L417-L427

What if I only know the server name, which API should I take?

**Comment by suchangshi** [comment]
1.If you want to get the ECS detail info by server name, we suggest to use: https://support.huaweicloud.com/en-us/api-ecs/en-us_topic_0094148850.html, 
with the SDK interface: "ListServersDetails";
for server ID, we suggest to use: https://support.huaweicloud.com/en-us/api-ecs/ecs_02_0104.html, with the SDK interface: "ShowServer".
2. Yes, we can use NovaShowServer to get a server by ID, and we suggest OpenStackAPIVersion setting to "compute 2.26".

**Comment by RainbowMango** [comment]
Thanks, @suchangshi, I picked `ListServersDetails` and `ShowServer` and they both works!
