### ISSUE TITLE
cluster的extendParam类型应为map[string]interface{}

### ISSUE THREAD

**Issue by clumsy456** [huaweicloud/huaweicloud-sdk-go-v3#20]
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/10fa274de65684828dfef919ec8dd0dba8daeab8/services/cce/v3/model/model_v3_cluster_spec.go#L60

当创建包月集群时，periodNum字段的value是数字，而不应是字符串。

在apiexplorer测试：
![image](https://user-images.githubusercontent.com/19684295/120325645-71c16d80-c31a-11eb-9ae5-fc190ddbccc5.png)
可以创建成功；
![image](https://user-images.githubusercontent.com/19684295/120325820-9f0e1b80-c31a-11eb-9fab-52358b601466.png)
创建失败，报错
![image](https://user-images.githubusercontent.com/19684295/120325900-b3eaaf00-c31a-11eb-925f-5284107d1379.png)

**Comment by wuchen-huawei** [comment]
你好，0.0.46 版本已经修复了，请确认下问题是否已解决。
