### ISSUE TITLE
CCE插件状态

### ISSUE THREAD

**Issue by clumsy456** [huaweicloud/huaweicloud-sdk-go-v3#22]
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/ea9a49088570d69ddf4f9cd312839510f073185c/services/cce/v3/model/model_addon_instance_status.go#L43

实测发现平台返回值有available类型，这个枚举要改一下。

**Comment by wuchen-huawei** [comment]
你好，请问具体调用的是哪个接口，能否提供一下接口URL和接口返回的内容？

**Comment by clumsy456** [comment]
ListAddonInstances接口，返回的item的status.status字段值为"available"。

**Comment by wuchen-huawei** [comment]
收到，问题已经定位到，会在下个版本修复（6.25日发布），感谢您的建议 ^-^

**Comment by wuchen-huawei** [comment]
你好，上面的问题在 6.21 发布的 0.0.48 版本中已解决，如使用中还有问题，请及时向我们反馈或者直接在华为云上提交工单，感谢您的建议。
