### ISSUE TITLE
各位使用 SDK 小伙伴还是多注意，真是对这个 go sdk 的规范有点心累，老是改函数名、移除函数之类的，完全不知道他们的规范是什么

### ISSUE THREAD

**Issue by zhb127** [huaweicloud/huaweicloud-sdk-go-v3#24]

**Comment by zhb127** [comment]
也是不明白，无关紧要的函数名变更是为了什么，单纯强迫症么

**Comment by mojocn** [comment]
我也来提点意见:
1. 函数式编程,option 构造器 很哆嗦
2. 大量标量指针来判断可选参数,而不是使用标量zero value 判断可选参数, 导致IDE不好部全属性.

**Comment by cupen** [comment]
还好啦，能在编译期发现的错误都不算大问题。可以版本号来标注，用 replace 锁住版本。:smiley: 

另外，同样作为用户，我倒觉得 SDK 这类“浅而平” 的项目优先级可以是: `易用 > 易维护 > 兼容性`。毕竟兼容性不好用户骂两句还会继续用，易用/易维护做不好就不是骂两句能完事的，没准会砍项目卷铺盖。

**Comment by zhb127** [comment]
> 还好啦，能在编译期发现的错误都不算大问题。可以版本号来标注，用 replace 锁住版本。😃
> 
> 另外，同样作为用户，我倒觉得 SDK 这类“浅而平” 的项目优先级可以是: `易用 > 易维护 > 兼容性`。毕竟兼容性不好我骂两句还会继续用，但易用/易维护做不好就不是骂两句能完事的，没准就没人用没人维护了，到时就砍项目卷铺盖。

😆，这个 issue 也是发生在多次以上的 SDK 升级不兼容而忍不住吐槽的，主要是我们的需求不一样，要对接 70% 的服务，也给他们提了很多需求，所以 SDK 必须升级，因此发现的问题比较多。

- 文件名包含 _window，macos 编译不通过
- struct 结构不对
- 枚举类型被删除，改成字符串类型

这些都经历过，后来也让他们发 changelog，新特性（增加函数、类型之类）也倒是没说什么。最头疼的是，今天计划要对接新特性，然后升级 SDK，引入一些不兼容（函数、类型改名之类，仔细看了源码是无关紧要的），这就比较无语，改完不兼容代码后，测试发现 SDK BUG，然后版本就得回退。。。反馈问题，等 SDK 重新发版。。。

当然，每个 SDK 都有一个从不稳定到文档的过程，可以理解，只不过对一些规范类的问题，导致的 SDK 兼容就比较无语了。
