### ISSUE TITLE
请问使用华为内网调用sdk的情况有配置 sdk proxy的方案么？ 不管是在SPEC VPN的网络下还是在内网openstack的VM上都会出现timeout的情况😂

### ISSUE THREAD

**Issue by acejarvis** [huaweicloud/huaweicloud-sdk-go-v3#25]
Scenario:
* 在内网openstack虚拟机上使用huaweicloud-sdk-go-v3 调用 ECS 创建服务器 API，长时间API没有返回任何response，提示timeout：
  ```bash
     [ERROR] Post "https://ecs.cn-north-1.myhuaweicloud.com/v1.1/017a290a8242480e82de8db804c1718d/cloudservers": 
     context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  ```
请问有什么特殊的proxy 需要在创建sdkClient的时候配置嘛？例如以下documentation中提到的样例代码：
```go
httpConfig.WithProxy(config.NewProxy().
    WithSchema("http").
    WithHost("proxy.huaweicloud.com").
    WithPort(80).
    WithUsername("testuser").
    WithPassword("password"))))
```

**Comment by wuchen-huawei** [comment]
你好，华为的内网由于spec的网络限制，无法调用生产环境的endpoint，配置proxy也会被拦截，这个SDK侧没有办法处理。如果只是想要测试SDK或者调用少量接口，建议以下两种方案：
1. 在 [API Explorer](https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=ECS&api=CreateServers) 上切换到 `代码示例` 选择SDK语言 `Go`，然后点击语言右侧按钮 `SDK代码示例调试`，在弹出的界面上进行调试
