### ISSUE TITLE
sdk 对部分region不支持，例如（cn-northeast-1）

### ISSUE THREAD

**Issue by greatcz** [huaweicloud/huaweicloud-sdk-go-v3#30]
是否是因为线上新加了region，但是没有更新sdk？

**Comment by mawenbo-huawei** [comment]
不同服务支持的region是不一样的，请问您使用的是哪个服务？

**Comment by greatcz** [comment]
> 不同服务支持的region是不一样的，请问您使用的是哪个服务？

ecs服务。（是这样的，我有一个遍历region同步ecs的需求，但是用目前的sdk，在遍历region获取ecs的时候，有部分region目前是不支持的）

**Comment by mawenbo-huawei** [comment]
ECS服务暂不支持region为 **cn-northeast-1**，您可以在[可用分区](https://developer.huaweicloud.com/endpoint?ECS)中查询支持的region。如您在使用上还有问题，请提交issue或者在华为云控制台上给对应的云服务提交工单。

**Comment by greatcz** [comment]
> ECS服务暂不支持region为 **cn-northeast-1**，您可以在[可用分区](https://developer.huaweicloud.com/endpoint?ECS)中查询支持的region。如您在使用上还有问题，请提交issue或者在华为云控制台上给对应的云服务提交工单。

十分感谢您的耐心回复~，我这边前面使用region列表的接口，用成了iam服务的，现在找到了ecs这边专有的获取可用区的接口，问题解决了。谢谢~

**Comment by mawenbo-huawei** [comment]
好的，那我这边就关闭issue了，祝您工作和生活愉快~
