### ISSUE TITLE
CreateServers 接口发现两个问题

### ISSUE THREAD

**Issue by lubingGalaxy** [huaweicloud/huaweicloud-sdk-go-v3#34]
1、CreateServers DryRun=true时，不能检查eip相关参数，比如Chargemode、Iptype
2、CreateServers 每个账号都有配额限制，如果两次提交间隔很短，则无法判断出超出配额。比如额度200，分两次提交，每次提交101台，本来第二次应该返回超出配额的错误，但如果两次间隔很短，则会返回202个id

**Comment by mawenbo-huawei** [comment]
根据您的问题描述，这个属于云服务接口的问题，请在华为云控制台上给对应的云服务提交工单。
