### ISSUE TITLE
model.GetCreateFunctionRequestBodyRuntimeEnum() 返回的runtime有误

### ISSUE THREAD

**Issue by 05lover** [huaweicloud/huaweicloud-sdk-go-v3#39]
现在的字符串是“Python 3.6”，正确的应该是“Python3.6”。同时官网API对照sdk给出的go示例中代码也有问题，现在是“model.GetCreateFunctionRequestBodyRuntimeEnum().PYTHON 3_6”，应该是“...PYTHON_3_6”

**Comment by mawenbo-huawei** [comment]
这个问题将在下个版本修复，感谢您的反馈！
