### ISSUE TITLE
client.InvokeFunction(request) panic

### ISSUE THREAD

**Issue by 05lover** [huaweicloud/huaweicloud-sdk-go-v3#40]
panic: interface conversion: interface {} is nil, not *model.InvokeFunctionResponse

**Comment by 05lover** [comment]
`

func (c *FunctionGraphClient) InvokeFunction(request *model.InvokeFunctionRequest) (*model.InvokeFunctionResponse, error) {
	
      requestDef := GenReqDefForInvokeFunction()

      if resp, err := c.HcClient.Sync(request, requestDef); err != nil {
        return nil, err
      } else {
        return resp.(*model.InvokeFunctionResponse), nil
      }}
`
return resp.(*model.InvokeFunctionResponse), nil 没有检查resp为空的情况

**Comment by mawenbo-huawei** [comment]
请问您使用的SDK版本号是多少，是否有调用报错时的代码？

**Comment by 05lover** [comment]
go version go1.17.5 darwin/amd64
代码就是官网invokefunction 给的sdk示例[https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=FunctionGraph&api=InvokeFunction](url)
函数代码：
import json

def handler (event, context):
    output =json.dumps(event)
    print("hello world")
    return output

**Comment by 05lover** [comment]
之前的请求没有传入body，所以我以为返回可能为空，但是我将部署的代码改成了
import json

def handler (event, context):
    value = {
        "msg": "Hello fg!"
    }    
    return json.dumps(value)
仍然没有返回内容，返回为InvokeFunctionResponse {}

**Comment by 05lover** [comment]
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/core/hc_http_client.go#L271
`err = jsoniter.Unmarshal(data, &reqDef.Response)`
这行代码把从resp中的body的内容按json格式解析放入reqDef.Response中，必须要key相同，才能解析出来。
而reqDef.Response只有几个key：
<img width="308" alt="截屏2022-02-24 下午8 23 29" src="https://user-images.githubusercontent.com/38162204/155523334-ec3cf4d8-3e6c-433e-9586-5483243e6dd6.png">
所以这样的实现肯定是有问题的。观察前面的代码：
`data, err := ioutil.ReadAll(resp.Response.Body)`
`for _, item := range reqDef.ResponseFields {
		if item.LocationType == def.Header {
`
而reqDef用GenReqDefForInvokeFunction() 生成时根本没有ResponseFields,所以也就没有header、body了


正确处理方式：
import json

def handler (event, context):
value = {
"Result": "Hello fg!"
}
return json.dumps(value)
python代码返回的json的key必须属于上图中response的几个key，这样就能拿到返回的结果了

**Comment by mawenbo-huawei** [comment]
> https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/core/hc_http_client.go#L271 `err = jsoniter.Unmarshal(data, &reqDef.Response)` 这行代码把从resp中的body的内容按json格式解析放入reqDef.Response中，必须要key相同，才能解析出来。 而reqDef.Response只有几个key： <img alt="截屏2022-02-24 下午8 23 29" width="308" src="https://user-images.githubusercontent.com/38162204/155523334-ec3cf4d8-3e6c-433e-9586-5483243e6dd6.png"> 所以这样的实现肯定是有问题的。
> 
> 正确处理方式： import json
> 
> def handler (event, context): value = { "Result": "Hello fg!" } return json.dumps(value) python代码返回的json的key必须属于上图中response的几个key，这样就能拿到返回的结果了

就是这样实现的，request和response中的字段是各云服务定义的，没有的字段是不会解析出来的

**Comment by 05lover** [comment]
OK，谢谢，了解了，可惜官方关于sdk的文档中没有提到这一点。

**Comment by mawenbo-huawei** [comment]
没事，接下来的版本会对文档说明做一些优化，感谢反馈。
