### ISSUE TITLE
request ContentType ”\n“换行问题

### ISSUE THREAD

**Issue by mx1052** [huaweicloud/huaweicloud-sdk-go-v3#42]
![image](https://user-images.githubusercontent.com/22515880/156526508-f8fb2cfc-2353-4e86-b99e-d500bbe1a9c3.png)
源码中返回的content type会有”/n“换行
![image](https://user-images.githubusercontent.com/22515880/156527359-6e292e9a-e276-4c66-9d75-46fc468fdead.png)

![image](https://user-images.githubusercontent.com/22515880/156526022-b05674fb-5ee5-47fe-bab7-c4b81d8ce134.png)

**Comment by mawenbo-huawei** [comment]
麻烦发一下调用接口的代码，谢谢！需要看一下`ListRepositoryTagsRequest`中的`ListRepositoryTagsRequestContentType`参数是如何指定的。
附上示例代码：
```go
contentType := swrModel.GetListRepositoryTagsRequestContentTypeEnum().APPLICATION_JSON
	request := &swrModel.ListRepositoryTagsRequest{
		ContentType: contentType,
	}
```

**Comment by mx1052** [comment]
> 麻烦发一下调用接口的代码，谢谢！需要看一下`ListRepositoryTagsRequest`中的`ListRepositoryTagsRequestContentType`参数是如何指定的。 附上示例代码：
> 
> ```go
> contentType := swrModel.GetListRepositoryTagsRequestContentTypeEnum().APPLICATION_JSON
> 	request := &swrModel.ListRepositoryTagsRequest{
> 		ContentType: contentType,
> 	}
> ```
你好，代码是这样的
我在macos M1处理器上用go1.17.7运行时没有问题的，同事用**macos intel处理器go1.17.6运行会出现content type换行**，另一个同事windows go.1.16.8也是ok。
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/22515880/156726197-55396f2b-64b2-4d70-9315-b1bcfdf4f877.png">

**Comment by asjdf** [comment]
m1 go1.20.0

```
swr.NewSwrClient(
	swr.SwrClientBuilder().
		WithRegion(region.ValueOf(regionId)).
		WithCredential(auth).
		Build()
).ListReposDetails(&model.ListReposDetailsRequest{
	ContentType: model.GetListReposDetailsRequestContentTypeEnum().APPLICATION_JSON,
})
```
可复现

**Comment by mawenbo-huawei** [comment]
> m1 go1.20.0
> 
> ```
> swr.NewSwrClient(
> 	swr.SwrClientBuilder().
> 		WithRegion(region.ValueOf(regionId)).
> 		WithCredential(auth).
> 		Build()
> ).ListReposDetails(&model.ListReposDetailsRequest{
> 	ContentType: model.GetListReposDetailsRequestContentTypeEnum().APPLICATION_JSON,
> })
> ```
> 
> 可复现

0.1.45版本已知问题，请使用之前的版本，或者等待下个版本修复该问题。

**Comment by asjdf** [comment]
> > m1 go1.20.0
> > ```
> > swr.NewSwrClient(
> > 	swr.SwrClientBuilder().
> > 		WithRegion(region.ValueOf(regionId)).
> > 		WithCredential(auth).
> > 		Build()
> > ).ListReposDetails(&model.ListReposDetailsRequest{
> > 	ContentType: model.GetListReposDetailsRequestContentTypeEnum().APPLICATION_JSON,
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可复现
> 
> 0.1.45版本已知问题，请使用之前的版本，或者等待下个版本修复该问题。

1.14版本及之后版本的 std json 库的性能已经优于 jsoniter，建议使用 std json 代替 jsoniter，可解决该问题。
