### ISSUE TITLE
ecs.UpdateServerMetadata seems to fail if built with go1.18

### ISSUE THREAD

**Issue by valerioj** [huaweicloud/huaweicloud-sdk-go-v3#49]
Hello

I have a program that requires huaweicloud-sdk-go-v3 (latest version; 0.0.89) for mainly management of ECS instances.

when the program is built with go1.16 there's no problem, but when built with go1.18, the function UpdateServerMetadata panics with "unexpected fault address"

I attach a small piece of code that can reproduce the error and the logs.
[sample.zip](https://github.com/huaweicloud/huaweicloud-sdk-go-v3/files/8729203/sample.zip)

**Comment by mawenbo-huawei** [comment]
Thank you for your feedback. I'll check this out.

**Comment by valerioj** [comment]
hello @mawenbo-huawei 
thanks for taking care of this. any news?

**Comment by matthiashinrichs** [comment]
Hello @mawenbo-huawei 
Are there any news on this topic?

**Comment by Huaweicloud-SDK** [comment]
The problem has been fixed.

**Comment by matthiashinrichs** [comment]
@Huaweicloud-SDK Thanks for your feedback. 
With the latest version of the SDK using more recent go versions (1.19.x and 1.20.x) are working correctly. So this ticket can be closed.
