### ISSUE TITLE
v3版本没有dns的sdk啊

### ISSUE THREAD

**Issue by felix-hxz** [huaweicloud/huaweicloud-sdk-go-v3#5]
v3版本没有dns的sdk啊，是要用老版本的嘛 老版本还能用不

**Comment by zhb127** [comment]
新旧版本混用吧。。

**Comment by wuchen-huawei** [comment]
V3版本目前还没有DNS的SDK，目前正在安排V3版本上线，您这边如果想用，可以先用DNS老版本的SDK，老版本还是可以用的。待新版本上线后，我们会再次回复这个Issue。

**Comment by jinnzy** [comment]
> V3版本目前还没有DNS的SDK，目前正在安排V3版本上线，您这边如果想用，可以先用DNS老版本的SDK，老版本还是可以用的。待新版本上线后，我们会再次回复这个Issue。

麻烦v3 rds上线了也回复一下

**Comment by xionghao-hw** [comment]
dns和rds的sdk均在新版本中提供，谢谢
