### ISSUE TITLE
Please abstract the client method into interface

### ISSUE THREAD

**Issue by Ericwww** [huaweicloud/huaweicloud-sdk-go-v3#50]
Hi, developer.

The method of each client is not be abstracted into interface, so that we can not use `mockgen` to generate mock code.

Now, for unit test, I have to wrap your client into a wrapper and abstract it. 

We will appreciate it if you could do the abstraction ASAP.

**Comment by nikpivkin** [comment]
Hi @Ericwww . Can't you use dependency injection and use your own interface?

**Comment by Ericwww** [comment]
Well, defining my own interface can resolve it indeed. Thanks for your remind. I will close this issue and mark it is resolved.
