### ISSUE TITLE
Panic in default_http_client

### ISSUE THREAD

**Issue by andrewbaxter** [huaweicloud/huaweicloud-sdk-go-v3#53]
Sometimes after `client.goHttpClient.Do(req)` `resp == nil` at https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/core/impl/default_http_client.go#L97 (for example, due to DNS errors).

Then `resp.Header.Get(...)` panics here: https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/core/impl/default_http_client.go#L121

**Comment by mawenbo-huawei** [comment]
This issue will be fixed in the next version

**Comment by mawenbo-huawei** [comment]
The issue has been fixed in v0.0.96
