### ISSUE TITLE
Version Incompatible with go 1.18.3

### ISSUE THREAD

**Issue by xuqiaobo** [huaweicloud/huaweicloud-sdk-go-v3#54]
when I integrate the current viersion into go 1.18.3 project, encounter new errors at here:
func (c *EcsClient) NovaShowServer(request *model.NovaShowServerRequest) (*model.NovaShowServerResponse, error) {
	requestDef := GenReqDefForNovaShowServer()

	if resp, err := c.HcClient.Sync(request, requestDef); err != nil {
		return nil, err
	} else {
		return resp.(*model.NovaShowServerResponse), nil
	}
}

the error follows:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xc3acaa]                      

goroutine 8 [running]:
github.com/modern-go/reflect2.(*frozenConfig).Type2(0xfda0e0, {0x125a560, 0xf9f1e0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/modern-go/reflect2@v1.0.1/reflect2.go:157 +0x4a
github.com/modern-go/reflect2.(*UnsafeMapType).Key(0xc0003daec0)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:53 +0x49
github.com/json-iterator/go.decoderOfMap(0xc0004a1170, {0x1257ea0?, 0xc0003daec0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_map.go:14 +0xe5
github.com/json-iterator/go._createDecoderOfType(0xc0004a1170, {0x1257ea0?, 0xc0003daec0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:182 +0x2c8
github.com/json-iterator/go.createDecoderOfType(0xc0004a1170, {0x1257ea0, 0xc0003daec0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc0004a1170, {0x1257ea0, 0xc0003daec0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.describeStruct(0xc0004a06f0, {0x1258080?, 0xc0004a07b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_extension.go:380 +0x6d0
github.com/json-iterator/go.decoderOfStruct(0xc0004a06f0, {0x1258080, 0xc0004a07b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:14 +0xb4
github.com/json-iterator/go._createDecoderOfType(0xc0004a06f0, {0x1258080?, 0xc0004a07b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:176 +0x410
github.com/json-iterator/go.createDecoderOfType(0xc0004a06f0, {0x1258080, 0xc0004a07b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc0004a06f0, {0x1258080, 0xc0004a07b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.decoderOfOptional(0xc0004a0750?, {0x1257f40?, 0xc0004a0750?})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:11 +0x5f
github.com/json-iterator/go._createDecoderOfType(0xc0004a06f0, {0x1257f40?, 0xc0004a0750})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:184 +0x452
github.com/json-iterator/go.createDecoderOfType(0xc0004a06f0, {0x1257f40, 0xc0004a0750})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc0004a06f0, {0x1257f40, 0xc0004a0750})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.describeStruct(0xc0004a02a0, {0x1258080?, 0xc0004a0360})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_extension.go:380 +0x6d0
github.com/json-iterator/go.decoderOfStruct(0xc0004a02a0, {0x1258080, 0xc0004a0360})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:14 +0xb4
github.com/json-iterator/go._createDecoderOfType(0xc0004a02a0, {0x1258080?, 0xc0004a0360})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:176 +0x410
github.com/json-iterator/go.createDecoderOfType(0xc0004a02a0, {0x1258080, 0xc0004a0360})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc0004a02a0, {0x1258080, 0xc0004a0360})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.decoderOfOptional(0xc0004a0300?, {0x1257f40?, 0xc0004a0300?})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:11 +0x5f
github.com/json-iterator/go._createDecoderOfType(0xc0004a02a0, {0x1257f40?, 0xc0004a0300})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:184 +0x452
github.com/json-iterator/go.createDecoderOfType(0xc0004a02a0, {0x1257f40, 0xc0004a0300})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc0004a02a0, {0x1257f40, 0xc0004a0300})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.describeStruct(0xc0002c76e8, {0x1258080?, 0xc0004a01b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_extension.go:380 +0x6d0
github.com/json-iterator/go.decoderOfStruct(0xc0002c76e8, {0x1258080, 0xc0004a01b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:14 +0xb4
github.com/json-iterator/go._createDecoderOfType(0xc0002c76e8, {0x1258080?, 0xc0004a01b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:176 +0x410
github.com/json-iterator/go.createDecoderOfType(0xc0002c76e8, {0x1258080, 0xc0004a01b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc0002c76e8, {0x1258080, 0xc0004a01b0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.(*frozenConfig).DecoderOf(0xc0002900a0, {0x1257f40, 0xc0004a00f0})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:114 +0x108
github.com/json-iterator/go.(*Iterator).ReadVal(0xc0001f82d0, {0xfc7860, 0xc000244f90})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:72 +0xe5
github.com/json-iterator/go.(*efaceDecoder).Decode(0xc0002495f0?, 0xc000238140, 0xc0002c7840?)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_dynamic.go:52 +0x159
github.com/json-iterator/go.(*Iterator).ReadVal(0xc0001f82d0, {0xf7c080, 0xc000238140})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:79 +0x103
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc0002900a0, {0xc00027e800?, 0x0?, 0x0?}, {0xf7c080, 0xc000238140})
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:348 +0xa5
github.com/json-iterator/go.Unmarshal(...)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/json-iterator/go@v1.1.10/adapter.go:16
github.com/huaweicloud/huaweicloud-sdk-go-v3/core.(*HcHttpClient).deserializeResponse(0xc00046a810?, 0xc0001f6000, 0xc0002380e0)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/huaweicloud/huaweicloud-sdk-go-v3@v0.0.84/core/hc_http_client.go:271 +0x8e7
github.com/huaweicloud/huaweicloud-sdk-go-v3/core.(*HcHttpClient).extractResponse(0xc00006f3e0?, 0xfc7800?, 0xc0002380e0)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/huaweicloud/huaweicloud-sdk-go-v3@v0.0.84/core/hc_http_client.go:200 +0x2c
github.com/huaweicloud/huaweicloud-sdk-go-v3/core.(*HcHttpClient).Sync(0xc000119680, {0xfc7800?, 0xc000004618?}, 0x1029dc0?)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/huaweicloud/huaweicloud-sdk-go-v3@v0.0.84/core/hc_http_client.go:71 +0x75
github.com/huaweicloud/huaweicloud-sdk-go-v3/services/ecs/v2.(*EcsClient).NovaShowServer(0xc0001f6220, 0xc00039e3a8?)
        D:/cloudrobotics/GO_HOME/pkg/mod/github.com/huaweicloud/huaweicloud-sdk-go-v3@v0.0.84/services/ecs/v2/ecs_client.go:510 +0x46
huaweicloud.com/cloudrobot/pkg/cloudservice/ecs.(*Client).ShowServerDetails(0xc0002c8060, {0xc0003d4450, 0x24})
        D:/cloudrobotics/GO_HOME/src/cloudrobotics/pkg/cloudservice/ecs/ecs_client.go:163 +0x9b

but when I use other go version, did not encounter like this

**Comment by mawenbo-huawei** [comment]
This issue will be fixed in the next version.
