### ISSUE TITLE
调用的服务接口超时时，SyncInvokeHttpWithExchange会抛出空指针

### ISSUE THREAD

**Issue by wxy8961230** [huaweicloud/huaweicloud-sdk-go-v3#55]
空指针截图如下：
![image](https://user-images.githubusercontent.com/22679705/177268886-a6b169ac-52df-48cd-a3e0-a6f66a7745fc.png)

接口超时后resp为nil，走到recordResponseInfo就会抛出空指针。
![image](https://user-images.githubusercontent.com/22679705/177268746-59586532-05e8-445e-bef7-f595143dc223.png)

**Comment by mawenbo-huawei** [comment]
用的是什么版本？ 更新到`0.0.96`版本再试试

**Comment by wxy8961230** [comment]
> 用的是什么版本？ 更新到`0.0.96`版本再试试

0.0.91 已升级。问题解决。谢谢。
