### ISSUE TITLE
关于default_http_client中listenRequest 对 request的clone导致新的request对象无法正确被httputil.DumpRequest解析的问题

### ISSUE THREAD

**Issue by stayNightL** [huaweicloud/huaweicloud-sdk-go-v3#56]
![image](https://user-images.githubusercontent.com/40538240/186396163-8468e9b2-025f-41be-be92-5dfb30a13fc1.png)
如图所示,在clone的过程中,会重新给req.body赋值, 这里其实有歧义:
1. dumprequest的结果带head等信息的,结果被覆给了req.body,这应该是个明显的错误
2. 如果是GET请求,req.body应该本来就是nil,这里直接赋值会有问题

基于已上两点,在二次dump中 会出现重复的请求的信息,原因是dump的实现中基于req.body是否是nil进行了一次copy 如图
![image](https://user-images.githubusercontent.com/40538240/186397245-97c4f9cf-e822-485d-a168-6b4f13fc24a0.png)

bug导致的效果是  GET请求会被打印两次 (敏感数据 就不上传了)

**Comment by mawenbo-huawei** [comment]
已收到反馈，会在近期的版本进行修复

**Comment by stayNightL** [comment]
> 已收到反馈，会在近期的版本进行修复

可以给出具体时间吗

**Comment by mawenbo-huawei** [comment]
0.0.108版本修复了一些相关的问题
