### ISSUE TITLE
RDS ListOffSiteInstances SDK Golang

### ISSUE THREAD

**Issue by kibalion2427** [huaweicloud/huaweicloud-sdk-go-v3#57]
I'm using the SDK golang documentation with this example
<img width="552" alt="image" src="https://user-images.githubusercontent.com/24326674/192073116-957fd6c0-94a7-499d-b973-74d96895c632.png">

The problem is I'm facing this compiler error:
`cannot use &offsetRequest (value of type *int64) as type *interface{} in assignment:
        *int64 does not implement *interface{} (type *interface{} is pointer to interface, not interface)`

**Comment by mawenbo-huawei** [comment]
Which version?

**Comment by kibalion2427** [comment]
> 

Go: 1.19

**Comment by mawenbo-huawei** [comment]
This is an error in defining the parameter type, I have sent the feedback to the RDS service.
This problem is expected to be fixed in next week's release.
If you are in a hurry, try this:
```go
request := &model.ListOffSiteInstancesRequest{}
	var offset interface{} = 5
	request.Offset = &offset
```

**Comment by kibalion2427** [comment]
Thanks for the support!
