### ISSUE TITLE
CreateVolume API for EVS doesn't return the Volume ID

### ISSUE THREAD

**Issue by kumarashit** [huaweicloud/huaweicloud-sdk-go-v3#6]
Used the sdk to create EVS disks. The CreateVolumeResponse sent has just the JobId. But as per the model, it should send the VolumeIds too.
Here is the response of Create Volume:

*%!(EXTRA model.CreateVolumeResponse=CreateVolumeResponse {"job_id":"ff80808174d52705017525ef77f45876"})*

**Comment by wuchen-huawei** [comment]
Hello, we have confirmed the problem above with the related R&D Engineer, and the reply is the response parameter `volume_ids` is in beta now, it's only available in some internal regions currently , and it will be available to all regions in the future.

**Comment by kumarashit** [comment]
Sure. Thanks
Will keep checking this for update
