### ISSUE TITLE
Translation to English

### ISSUE THREAD

**Issue by leodahal4** [huaweicloud/huaweicloud-sdk-go-v3#60]
Can the documentation be also provided in **English**, so developers from other country can find it easy to work with.
Since, right now it's a lot hard to translate each comments and then re-phrase the code scenario.

**Comment by Huaweicloud-SDK** [comment]
You can refer to the API Explorer International Site: [https://console-intl.huaweicloud.com/apiexplorer/?locale=en-us#/overview?api=product&sdk=sdk&sample=code](https://console-intl.huaweicloud.com/apiexplorer/?locale=en-us#/overview?api=product&sdk=sdk&sample=code)
