### ISSUE TITLE
model.phone 的 VncEnable 字段，模型定义为 *string， http 返回 bool  

### ISSUE THREAD

**Issue by chengjk** [huaweicloud/huaweicloud-sdk-go-v3#68]
{"status_code":200,"request_id":"329b574477dd15b11bdef128f5e30bfe","error_code":"","error_message":"model.ListCloudPhonesResponse.Phones: []model.Phone: model.Phone.VncEnable: ReadString: expects \" or n, but found f, error found in #10 byte of

**Comment by mawenbo-huawei** [comment]
收到，已反馈给云手机服务
