### ISSUE TITLE
It seems that the `NewBaseInvoker` method will not pass the `extraHeader` in `HcHttpClient` to the `headers` in `BaseInvoker`

### ISSUE THREAD

**Issue by Ericwww** [huaweicloud/huaweicloud-sdk-go-v3#73]
**Is this a bug or feature?**

I construct a HcHttpClient with PreInvoke

```golang
const defaultUserAgent = "xxxxx"

func NewClient(cred *global.Credentials, skipVerify bool) *Client {
	hcHttpClient := v0.ServiceClientBuilder().
		WithCredential(cred).
		WithHttpConfig(
			config.DefaultHttpConfig().
				WithIgnoreSSLVerification(skipVerify),
		).
		Build().
		PreInvoke(map[string]string{
			"User-Agent": defaultUserAgent,
		})
	return &Client{
		hcHttpClient: hcHttpClient,
	}
}
```

But the `PreInvoke` not affect when I call `Invoke` method on some API's Invoker. 

Like this

```golang
invoker := Client.XXXXApiInvoker(req)
resp, err := invoker.Invoke()
```

When I got a request from sdk, I can not find my custom user-agent by this way.
![image](https://github.com/huaweicloud/huaweicloud-sdk-go-v3/assets/24605603/257ad875-05b5-41ca-b389-a9dfe55b9856)

I think the problem is at this function: https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/3e4dcb2c0a9a75b75976cc6cc9c9327e727d9c4d/core/invoker/invoker.go#L47

**Comment by mawenbo-huawei** [comment]
`PreInvoke` is marked as `Deprecated`, refer to [custom-request-headers.](https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/README.md#71-custom-request-headers-top)
