### ISSUE TITLE
使用sdk调用codearts repo  api 查询 commitdiff 信息返回错误，用 API Explorer调试接口正常

### ISSUE THREAD

**Issue by Corner-W** [huaweicloud/huaweicloud-sdk-go-v3#75]
**演示代码：**
`package apis

import (
	"fmt"
	"github.com/huaweicloud/huaweicloud-sdk-go-v3/core/auth/basic"
	codehub "github.com/huaweicloud/huaweicloud-sdk-go-v3/services/codehub/v3"
	"github.com/huaweicloud/huaweicloud-sdk-go-v3/services/codehub/v3/model"
	region "github.com/huaweicloud/huaweicloud-sdk-go-v3/services/codehub/v3/region"
)

func CommitDiff() {

	ak := "xxx" // 隐藏
	sk := "xxx"

	auth := basic.NewCredentialsBuilder().
		WithAk(ak).
		WithSk(sk).
		Build()

	client := codehub.NewCodeHubClient(
		codehub.CodeHubClientBuilder().
			WithRegion(region.ValueOf("cn-north-4")).
			WithCredential(auth).
			Build())

	request := &model.ShowDiffCommitRequest{}
	request.RepoId = int32(2279062)
	request.Sha = "9fbfaa464e2b5f8108dbdbb9dd9dfc5b2d621e35"
	response, err := client.ShowDiffCommit(request)
	if err == nil {
		fmt.Println("succefully!!")
		fmt.Printf("%+v\n", response)
	} else {
		fmt.Println("failed!!")
		fmt.Println(err.Error())
	}

	// fmt.Println(response.String())
}
`
返回err ：
{"status_code":200,"request_id":"3ed522f27272539c34d63a8a4063b137","error_code":"","error_message":"model.ShowDiffCommitResponse.Result: []model.DiffCommitInfo: model.DiffCommitInfo.Diff: ReadBool: expect t or f, but found \", error found in #10 byte of ...|[{\"diff\":\"@@ -0,0 +1|..., bigger context ...|{\"result\":[{\"diff\":\"@@ -0,0 +1,12 @@\\n+package main\\n+\\n+import (\\n+\\t|...","encoded_authorization_message":""}

**Comment by mawenbo-huawei** [comment]
这个问题已反馈给codehub服务
