### ISSUE TITLE
[AS] creating scaling policy failed as request body error

### ISSUE THREAD

**Issue by RainbowMango** [huaweicloud/huaweicloud-sdk-go-v3#8]
I tried to create a scaling policy as follows:
https://github.com/kubernetes/autoscaler/blob/ef0497e31f60f489c879a4aa34d9134ff30ea55e/cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go#L204-L221

But I encountered `AS.0022` error:
```
W1103 12:41:16.449161       1 huaweicloud_service_manager.go:347] create scaling policy failed. policy: CreateScalingPolicyRequest 
{"body":{"scaling_policy_name":"huaweicloudautoscaler","scaling_group_id":"e7c3f6ff-d6b3-4b22-b809-47a22c180276","scaling_policy_type":"SCHEDULED","scheduled_policy":{"launch_time":{}},"scaling_policy_action":{"operation":"ADD","instance_number":1}}}, error: {"status_code":400,"request_id":"30acda2b0a86fa73f5d6ce9eb8610ca8","error_code":"AS.0022","error_message":"request body error"}
```
```json
{
    "body": {
        "scaling_policy_name": "huaweicloudautoscaler", 
        "scaling_group_id": "e7c3f6ff-d6b3-4b22-b809-47a22c180276", 
        "scaling_policy_type": "SCHEDULED", 
        "scheduled_policy": {
            "launch_time": { }
        }, 
        "scaling_policy_action": {
            "operation": "ADD", 
            "instance_number": 1
        }
    }
}
```

**Comment by RainbowMango** [comment]
Does this due to the launch_time is empty?
There is a similar issue, please refer to #7 .

**Comment by RainbowMango** [comment]
After update to [v0.0.20-beta](https://github.com/huaweicloud/huaweicloud-sdk-go-v3/releases/tag/v0.0.20-beta), the launch_time can be marshed correctly as follows:
```
{
    "body": {
        "scaling_policy_name": "huaweicloudautoscaler", 
        "scaling_group_id": "e7c3f6ff-d6b3-4b22-b809-47a22c180276", 
        "scaling_policy_type": "SCHEDULED", 
        "scheduled_policy": {
            "launch_time": "2020-11-04T04:19:15Z" // not empty anymore
        }, 
        "scaling_policy_action": {
            "operation": "ADD", 
            "instance_number": 1
        }
    }
}
```

But, the launch_time format is `2006-01-02T15:04:05Z` which not match the requirement(`YYYY-MM-DDThh:mmZ`):
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/8733c595be33e3f957c7532bfa0c091fc2731571/services/as/v1/model/model_scheduled_policy.go#L20-L21

**Comment by RainbowMango** [comment]
The error code as follows:
```
error: {"status_code":400,"request_id":"5c64c1d382f5bc667fa38a9798f62c49","error_code":"AS.3009","error_message":"The format of parameter lanchTime is incorrect."}
```

**Comment by wuchen-huawei** [comment]
Hello, the SDK of AS has been optimized totally since version [0.0.45](https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/master/CHANGELOG.md#0045-2021-05-25), it's recommended to use this version.

If there is still a problem in use, please comment under this issue or submit a ticket on HuaweiCloud, thank you.

**Comment by RainbowMango** [comment]
Hi @wuchen-huawei.
Seems I've updated to a new SDK version.
